# Generated by Django 5.1.2 on 2024-10-17 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_habitacion_medicamento_residente_habitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitante_nombre', models.CharField(max_length=100)),
                ('visitante_identificacion', models.CharField(max_length=20)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='core.residente')),
            ],
        ),
    ]
